In [53]:
import pandas as pd
import numpy as np
data=pd.read_csv("zoo_data.csv")
data

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0           1         1         0     0     4     0         0        1     1  
1           1         1         0     0     4     1         0        1     1  
2           1         0         0     1     0     1         0        0     4  
3           1         1         0     0     4     0         0        1     1  
4           1         1         0     0     4     1         0        1     1  
..        ...       ...       ...   ...   ...   ...       ...      ...   ...  
96          1         1         0     0     2     1         0        1     1  
97          0         1         1     0     6     0         0        0     6  
98          1         1         0     0     4     1         0        1     1  
99          0         1         0     0     0     0         0        0     7  
100         1         1         0     0     2     1         0        0     2  

[101 rows x 17 columns]

In [54]:
x1=data['hair'].values
x2=data['feathers'].values
x3=data['eggs'].values
x4=data['milk'].values
x5=data['airborne'].values
x6=data['aquatic'].values
x7=data['predator'].values
x8=data['toothed'].values
x9=data['backbone'].values
x10=data['breathes'].values
x11=data['venomous'].values
x12=data['fins'].values
x13=data['legs'].values
x14=data['tail'].values
x15=data['domestic'].values
x16=data['catsize'].values
y =data['type'].values

In [55]:
X = np.array(list(zip(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16)))
X

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0]])

In [56]:
Y=y
Y

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2])

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.25)

In [71]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn import tree

decision = tree.DecisionTreeClassifier(criterion='gini')
decision.fit(X_train,y_train)

y_predict=decision.predict(X_test)
y_score = accuracy_score(y_test,y_predict)
print('Accuracy: ', y_score)
y_test

Accuracy:  0.9615384615384616


array([7, 7, 2, 1, 4, 1, 1, 1, 4, 2, 7, 2, 7, 1, 1, 4, 1, 6, 1, 4, 1, 1,
       2, 6, 2, 4])

In [68]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         5
           6       1.00      0.50      0.67         2
           7       0.80      1.00      0.89         4

    accuracy                           0.96        26
   macro avg       0.96      0.90      0.91        26
weighted avg       0.97      0.96      0.96        26



In [70]:
print(confusion_matrix(y_test,y_predict))

[[10  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  1  1]
 [ 0  0  0  0  4]]
