In [36]:
import pandas as pd
data=pd.read_csv("samp.csv")
data

x1   x2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0

In [37]:
data["x1"]

0    5.9
1    4.6
2    6.2
3    4.7
4    5.5
5    5.0
6    4.9
7    6.7
8    5.1
9    6.0
Name: x1, dtype: float64

In [60]:
import math 
cluster1=[]
cluster2=[]
cluster3=[]
cl1=[6.2,3.2]
cl2=[6.6,3.7]
cl3=[6.5,3.0]
def euc(a,b):
    d1=math.sqrt((cl1[0]-a)**2 + (cl1[1]-b)**2)
    d2=math.sqrt((cl2[0]-a)**2 + (cl2[1]-b)**2)
    d3=math.sqrt((cl3[0]-a)**2 + (cl3[1]-b)**2)
    md=min(d1,d2,d3)
    if(md==d1):
        cluster1.append([a,b])
    elif(md==d2):
        cluster2.append([a,b])
    else:
        cluster3.append([a,b])

In [61]:
for i in range(0,10):
    euc(data['x1'][i],data['x2'][i])
    
print("cluster1 : ",cluster1)
print("cluster2 : ",cluster2)
print("cluster3 : ",cluster3)

cluster1 :  [[5.9, 3.2], [4.6, 2.9], [4.7, 3.2], [5.0, 3.0], [4.9, 3.1], [5.1, 3.8], [6.0, 3.0]]
cluster2 :  [[5.5, 4.2]]
cluster3 :  [[6.2, 2.8], [6.7, 3.1]]


In [2]:
import numpy as np
import pandas as pd
from copy import deepcopy


def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

In [9]:
def main():
    k = 3
    X = pd.read_csv('samp.csv',index_col=False)
    #print(X)

    x1 = X['x1'].values
    x2 = X['x2'].values
    X = np.array(list(zip(x1, x2)))
    print("X value\n",X,"\n")
    C_x = [6.2, 6.6 ,6.5]
    C_y = [3.2, 3.7, 3.0]
    Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
    print("Centroid value\n",Centroid,"\n")


if __name__ == "__main__": 
    main()

X value
 [[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]] 

Centroid value
 [[6.2 3.2]
 [6.6 3.7]
 [6.5 3. ]] 



In [18]:
def main():
    k = 3
    X = pd.read_csv('samp.csv',index_col=False)
    print(X,"\n")

    x1 = X['x1'].values
    x2 = X['x2'].values
    X = np.array(list(zip(x1, x2)))
    print(X,"\n")
    C_x = [6.2, 6.6 ,6.5]
    C_y = [3.2, 3.7, 3.0]
    Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
    print("Initial Centroids")
    print(Centroid.shape,"\n")

    Centroid_old = np.zeros(Centroid.shape)
    print(Centroid_old,"\n")
    # Cluster Lables(0, 1, 2)
    clusters = np.zeros(len(X))
    print(clusters,"\n")
    error = euclidean(Centroid, Centroid_old, None)
    print(error,"\n")
    iterr = 0
    # Loop will run till the error becomes zero
    while error != 0:
        # Assigning each value to its closest cluster
        iterr = iterr + 1
        for i in range(len(X)):
            #print(X[i])
            distances = euclidean(X[i], Centroid)
            #print(distances)
            cluster = np.argmin(distances)
            clusters[i] = cluster

        print(clusters,"\n")
        Centroid_old = deepcopy(Centroid)
        
        # Finding the new centroids by taking the Mean
        for p in range(k):
            points = [X[j] for j in range(len(X)) if clusters[j] == p]
            Centroid[p] = np.mean(points, axis=0)
        print(" Centre of the clusters after ", iterr," Iteration \n", Centroid,"\n")
        error = euclidean(Centroid, Centroid_old, None)
        print("Error  ... ",error,"\n")  
    

if __name__ == "__main__": 
    main()


    x1   x2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0 

[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]] 

Initial Centroids
(3, 2) 

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

12.537144692236463 

[0. 0. 2. 0. 1. 0. 0. 2. 0. 0.] 

 Centre of the clusters after  1  Iteration 
 [[5.1714287 3.1714287]
 [5.5       4.2      ]
 [6.45      2.95     ]] 

Error  ...  1.5886393 

[2. 0. 2. 0. 1. 0. 0. 2. 1. 2.] 

 Centre of the clusters after  2  Iteration 
 [[4.8   3.05 ]
 [5.3   4.   ]
 [6.2   3.025]] 

Error  ...  0.5484787 

[2. 0. 2. 0. 1. 0. 0. 2. 1. 2.] 

 Centre of the clusters after  3  Iteration 
 [[4.8   3.05 ]
 [5.3   4.   ]
 [6.2   3.025]] 

Error  ...  0.0 

